# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo.xci
# IP: The module: 'sd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo.xci
# IP: The module: 'sd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
