# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out.xci
# IP: The module: 'fifo_16_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_out'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out.xci
# IP: The module: 'fifo_16_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
