# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.cache/wt [current_project]
set_property parent.project_path C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/data_convert.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/ddr3_controller.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/define.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/imports/modelsim/ddr3_sig_generator.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/fifo_256to16_series.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/fifo_series.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/fmc_data_compare.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/req_generator.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/imports/new/sd_ctrl_top.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/imports/new/sd_init.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/imports/new/sd_read.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/imports/new/sd_read_photo.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/imports/new/sd_write.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/imports/new/top_sd_photo.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/uart_data_convert.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/uart_top.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/uart_tx.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/vga_disp.v
  C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/new/ddrtovga_top.v
}
read_ip -quiet C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/clk_convert/clk_convert.xci
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/clk_convert/clk_convert_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/clk_convert/clk_convert.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/clk_convert/clk_convert_ooc.xdc]

read_ip -quiet C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/DDR3_CONTROL/ip/DDR3_CONTROL/DDR3_CONTROL.xci
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/DDR3_CONTROL/ip/DDR3_CONTROL/DDR3_CONTROL/user_design/constraints/DDR3_CONTROL.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/DDR3_CONTROL/ip/DDR3_CONTROL/DDR3_CONTROL/user_design/constraints/DDR3_CONTROL_ooc.xdc]

read_ip -quiet C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/sd_fifo/sd_fifo_ooc.xdc]

read_ip -quiet C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big.xci
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big_ooc.xdc]

read_ip -quiet C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_small/ddr_fifo_small.xci
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_small/ddr_fifo_small.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_small/ddr_fifo_small_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_small/ddr_fifo_small_ooc.xdc]

read_ip -quiet C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_256_ddr/fifo_256_ddr.xci
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_256_ddr/fifo_256_ddr.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_256_ddr/fifo_256_ddr_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_256_ddr/fifo_256_ddr_ooc.xdc]

read_ip -quiet C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out.xci
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/fifo_16_out/fifo_16_out_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/constrs_1/new/ddrtovga.xdc
set_property used_in_implementation false [get_files C:/Users/gyz/Desktop/ddrtovga/fmc_imput2/my_ddr_to_vga/my_ddr_to_vga.srcs/constrs_1/new/ddrtovga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ddrtovga_top -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ddrtovga_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ddrtovga_top_utilization_synth.rpt -pb ddrtovga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
