# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ddrtovga.xdc

# IP: ip/clk_convert/clk_convert.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_convert || ORIG_REF_NAME==clk_convert} -quiet] -quiet
