# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ddrtovga.xdc

# IP: ip/fmc_fifo/fmc_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_fifo || ORIG_REF_NAME==fmc_fifo} -quiet] -quiet
