# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big.xci
# IP: The module: 'ddr_fifo_big' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_fifo_big'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_fifo_big'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_fifo_big'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big.xci
# IP: The module: 'ddr_fifo_big' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_fifo_big'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_fifo_big'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gyz/Desktop/ddrtovga/mine/my_ddr_to_vga/my_ddr_to_vga.srcs/sources_1/ip/ddr_fifo_big/ddr_fifo_big_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_fifo_big'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
